blocked_list = [
    "#2020MAMA",
    "#ALLBLUE2022",
    "#AMAS",
    "#AMAs",
    "#ARIAsHarryStyles",
    "#ATEEZ",
    "#ATEEZ",
    "#AmericaDecentForAll",
    "#BTSxBBMAs",
    "#Biden2020",
    "#BiggBoss14Finale",
    "#ENDBADGOVERNANCE",
    "#ENDSARS",
    "#ElectionResults2020",
    "#EndBadGovernmentinNIGERIA",
    "#EndSWAT",
    "#EndSars",
    "#EndsSARS",
    "#ExcitedToSeeALDEN",
    "#FlipTexasBlue",
    "#IStandWithVirat",
    "#MAMAVOTE",
    "#MTVBTS",
    "#MissUniversePhilippines",
    "#PCAs",
    "#RahulVaidya",
    "#StanWorld",
    "#StopKillingNigerianYouth",
    "#SugarDaddySerious",
    "#Sugarmummy",
    "#TDYAwards",
    "#TRUMPPENCE2020",
    "#Times_City_Building_LED",
    "#TrumpIsCompromised",
    "#USAelection2020",
    "#VoterSuppression",
    "#VotersDecided",
    "#maturewomen",
    "#nakedeyes",
    "#occupyNigeria",
    "#robux",
    "#rtmejoebiden",
    "#sugardaddy",
    "#sugardaddyallowance",
    "#sugardaddylegit",
    "#sugarmomma",
    "#takeshower",
    "AMAs",
    "ATTENTION CARATS",
    "Ammar Campa-Najjar for Congress",
    "Ammar Campa-Najjar",
    "Artist Of The Year",
    "B0TTT0M",
    "B0t",
    "BIDEN",
    "BLACKPINK DESERVES TO WIN.",
    "Biden",
    "Bot Spotting",
    "DJT is down so far in the polls",
    "Democrats",
    "EndSARS",
    "FAT BURN. WEIGHT LOSS. NOOTROPICS. ENERGY.",
    "GOP legislatures",
    "Georgia’s runoff races",
    "Hillary Clinton",
    "I just donated to @ACampaNajjar for Congress!",
    "I just gave to Fair Fight!",
    "Joe Biden",
    "PCAs",
    "Pathetic PayPig",
    "Recount for Dan Forest",
    "Roblox",
    "Robux",
    "SUGAR DADDY",
    "SugarDaddySerious"
    "Suicide",
    "TRUMP",
    "Trump",
    "bts",
    "dick",
    "followandrt2win",
    "help Ateez win",
    "kpop cpop fancam views nsfw",
    "presidential election",
    "retweeejt",
    "retweet to win nothing",
    "robux",
    "sugar daddy",
    "sugar momma",
    "sugardaddy",
    "sugarmummy",
    "tRump",
    "#14thHeadies",
]